import re
from typing import List, Dict, Any
from app.core.config import settings

class NginxConfigGenerator:
    def __init__(self, domain=None, reality_domain=None, is_master=False):
        # Если параметры не переданы (например, на мастере), берем из settings
        self.domain = domain or settings.panel_domain
        self.reality_domain = reality_domain or settings.reality_dest_domain
        self.is_master = is_master
        
        # Данные панели нужны только если это Мастер-нода
        if self.is_master:
            self.panel_path = settings.panel_secret_path.strip("/")
            self.sub_path = settings.sub_path.strip('/')
            self.panel_port = "8000"
            self.sub_port = "8000"
        
        self.escaped_domain = re.escape(self.domain)
        self.escaped_reality = re.escape(self.reality_domain)

    def generate_placeholder_html(self) -> str:
        return f"""
<!DOCTYPE html>
<html lang="en">
<head>    
<meta charset="UTF-8">
<title>Site Placeholder</title>
<style>
body {{ font-family: Arial, sans-serif; text-align: center; margin-top: 50px; background-color: #f4f4f9; }}
h1 {{ color: #333; }}
p {{ color: #666; }}
</style>
</head>
<body>
<h1>Welcome to {self.domain}</h1>
<p>This is a placeholder page generated by Anaconduit.</p>
</body>
</html>
"""

    def generate_main_conf(self) -> str:
        return f"""
user nginx;
worker_processes auto;
pid /run/nginx.pid;

events {{
    worker_connections 4096;
}}

stream {{
    resolver 127.0.0.11 ipv6=off valid=30s;
    log_format proxy '$remote_addr [$time_local] '
                     '$protocol $status $bytes_sent $bytes_received '
                     '$session_time "$upstream_addr" '
                     'sni="$ssl_preread_server_name"';

    access_log /var/log/nginx/stream_access.log proxy;
    proxy_connect_timeout 2s; 
    proxy_timeout 1h; 
    tcp_nodelay on;
    include /etc/nginx/stream-enabled/*.conf;
}}

http {{
    include       mime.types;
    default_type  application/octet-stream;

    map $http_upgrade $connection_upgrade {{
        default upgrade;
        ''      close;
    }}
    set_real_ip_from  172.18.0.0/16;
    set_real_ip_from  10.0.0.0/8;
    set_real_ip_from  192.168.0.0/16;
    
    real_ip_header    proxy_protocol;
    real_ip_recursive on;
    
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    'rt=$request_time ua="$http_user_agent" ';
    
    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;
    
    http2_max_concurrent_streams 1000;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    include /etc/nginx/sites-enabled/*;
    include /etc/nginx/user-conf.d/*.conf;
}}
"""

    def generate_stream_conf(self, inbounds: List[Dict], static_inbounds: List[Dict]) -> str:
        map_entries = []
        seen = set()
        for ib in inbounds + static_inbounds:
            sni = ib["sni"].lower().strip().split(":")[0]
            if sni in seen: continue
            seen.add(sni)
            backend = ib.get("backend_host", "anaconduit_xray")
            map_entries.append(f"    {sni} {backend}:{ib['port']};")
        
        return f"""
map $ssl_preread_server_name $backend {{
    hostnames;
{chr(10).join(map_entries)}
    default anaconduit_xray:8443;
}}

server {{
    listen 443;
    listen [::]:443;
    proxy_pass $backend;
    ssl_preread on;
    proxy_protocol on;
    proxy_connect_timeout 10s;
    proxy_timeout 1h;
}}
"""

    def generate_sites_conf(self) -> Dict[str, str]:
        # 1. Редирект с HTTP на HTTPS (общий для всех)
        redirect = f"""
server {{
    listen 80;
    listen [::]:80;
    server_name {self.domain} {self.reality_domain};
    return 301 https://$host$request_uri;
}}
"""
        
        # Подготовка блока панели только для мастера
        panel_location = ""
        if self.is_master:
            panel_location = f"""
    location /{self.panel_path} {{
        proxy_pass http://anaconduit_backend:{self.panel_port};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $proxy_protocol_addr;
        proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }}
"""

        # 2. Основной домен (Панель + xHTTP + Заглушка)
        domain = fr"""
server {{
    listen 7443 ssl proxy_protocol;
    listen [::]:7443 ssl proxy_protocol;
    http2 on;
    server_name {self.domain};

    include /etc/nginx/snippets/user-*.conf;
    port_in_redirect off;

    root /var/www/html/;
    index index.html index.htm;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate     /etc/nginx/certs/live/{self.domain}/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/{self.domain}/privkey.pem;

    server_tokens off;
    if ($host !~* ^(.+\.)?{self.escaped_domain}$ ){{ return 444; }}

    location / {{
        root /var/www/html/;
        index index.html;
        try_files $uri /index.html;
    }}
    
    {panel_location}

    include /etc/nginx/snippets/xui-common-locations.conf;
}}
"""

        # 3. Домен для Reality (Маскировка)
        reality = fr"""
server {{
    listen 9443 ssl proxy_protocol;
    listen [::]:9443 ssl proxy_protocol;
    http2 on;
    server_name {self.reality_domain};
    
    set_real_ip_from  172.18.0.0/16;
    set_real_ip_from  10.0.0.0/8;
    set_real_ip_from  192.168.0.0/16;
    real_ip_header    proxy_protocol;
    real_ip_recursive on;

    root /var/www/html/;
    index index.html index.htm;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate     /etc/nginx/certs/live/{self.reality_domain}/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/{self.reality_domain}/privkey.pem;

    server_tokens off;
    if ($host !~* ^(.+\.)?{self.escaped_reality}$ ){{ return 444; }}

    location / {{
        root /var/www/html/;
        index index.html;
        try_files $uri /index.html;
    }}

    include /etc/nginx/snippets/xui-common-locations.conf;
}}
"""
        return {
            "80-redirect.conf": redirect, 
            "main-domain.conf": domain, 
            "reality-domain.conf": reality
        }

    def generate_snippet_conf(self, xhttp_inbounds: List[Dict]) -> str:
        panel_blocks = ""
        if self.is_master:
            panel_blocks = f"""
# Панель управления (Только для Master)
location /{self.panel_path}/ {{
    resolver 127.0.0.11 valid=30s;
    proxy_pass http://anaconduit_backend:{self.panel_port};
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $proxy_protocol_addr;
    proxy_set_header X-Forwarded-For $proxy_protocol_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}}

# Подписки (Только для Master)
location /{self.sub_path}/ {{
    resolver 127.0.0.11 valid=30s;
    proxy_pass http://anaconduit_backend:{self.sub_port};
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $proxy_protocol_addr;
    proxy_set_header X-Forwarded-For $proxy_protocol_addr;
}}
"""
        
        x_locs = []
        for xi in xhttp_inbounds:
            path = xi['path'].lstrip('/')
            x_locs.append(f"""
location /{path} {{
    grpc_pass grpc://unix:/run/xray/{xi['tag']}.sock;
    grpc_buffer_size          16k;
    grpc_socket_keepalive     on;
    grpc_read_timeout         1h;
    grpc_send_timeout         1h;
    grpc_set_header Connection         "";
    grpc_set_header Host               $host;
    grpc_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    grpc_set_header X-Forwarded-Proto  $scheme;
}}""")

        router_block = """
# Универсальный роутер Xray
location ~ ^/(?P<fwdport>\\d+)/ {
    resolver 127.0.0.11 valid=30s;
    client_max_body_size 0;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_socket_keepalive on;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $proxy_protocol_addr;
    proxy_set_header X-Forwarded-For $proxy_protocol_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    if ($content_type ~* "GRPC") {
        grpc_pass grpc://anaconduit_xray:$fwdport;
        break;
    }
    proxy_pass http://anaconduit_xray:$fwdport;
}
"""
        return f"{panel_blocks}\n" + "\n".join(x_locs) + router_block