networks:
  anaconduit_net:
    name: anaconduit_net   # 🔹 задаём точное имя
    driver: bridge

services:
  backend:
    build: .
    container_name: anaconduit_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      HOST_DATA_PATH: ${HOST_DATA_PATH}
      # Явно прокидываем DATABASE_URL, чтобы SQLAlchemy её видела
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_DATA_PATH}:/app/data
    networks:
      - anaconduit_net  # 🔹 подключаем к сети


