networks:
  anaconduit_net:
    name: anaconduit_net   # 🔹 задаём точное имя
    driver: bridge

services:
  backend:
    build: .
    container_name: anaconduit_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HOST_DATA_PATH=${HOST_DATA_PATH}
      - DATABASE_URL=${DATABASE_URL}
      - PROJECT_ROOT=/repo
    volumes:
      - .:/repo  # 🔹 Теперь и на хосте, и в контейнере путь будет резолвиться правильно
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_DATA_PATH}:/app/data
    networks:
      - anaconduit_net  # 🔹 подключаем к сети
          


