"""add_node_in_db

Revision ID: 347c97f904f8
Revises: e72da506a826
Create Date: 2026-04-18 10:49:44.444082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347c97f904f8'
down_revision: Union[str, Sequence[str], None] = 'e72da506a826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("PRAGMA foreign_keys=OFF;")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('api_url', sa.String(), nullable=False),
    sa.Column('reality_server_name', sa.String(), nullable=False),
    sa.Column('secret_token', sa.String(), nullable=False),
    sa.Column('desired_version', sa.Integer(), nullable=True),
    sa.Column('applied_version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes'))
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_id'), ['id'], unique=False)

    op.create_table('node_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_payload', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_node_configs_node_id_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_configs'))
    )
    with op.batch_alter_table('inbounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_inbounds_node_id_nodes'), 'nodes', ['node_id'], ['id'])

    with op.batch_alter_table('outbounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_outbounds_node_id_nodes'), 'nodes', ['node_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('routing_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_routing_rules_node_id_nodes'), 'nodes', ['node_id'], ['id'], ondelete='CASCADE')
    op.execute("PRAGMA foreign_keys=ON;")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("PRAGMA foreign_keys=OFF;")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routing_rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_routing_rules_node_id_nodes'), type_='foreignkey')
        batch_op.drop_column('node_id')

    with op.batch_alter_table('outbounds', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_outbounds_node_id_nodes'), type_='foreignkey')
        batch_op.drop_column('node_id')

    with op.batch_alter_table('inbounds', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inbounds_node_id_nodes'), type_='foreignkey')
        batch_op.drop_column('node_id')

    op.drop_table('node_configs')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_id'))

    op.drop_table('nodes')
    op.execute("PRAGMA foreign_keys=ON;")
    # ### end Alembic commands ###
