"""add_outbounds_and_rules

Revision ID: 6c6fcdcd9592
Revises: 49517b025649
Create Date: 2026-04-01 18:04:18.767136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6fcdcd9592'
down_revision: Union[str, Sequence[str], None] = '49517b025649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('stream_settings', sa.JSON(), nullable=True),
    sa.Column('mux', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbounds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbounds_tag'), ['tag'], unique=True)

    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outbound_tag', sa.String(), nullable=False),
    sa.Column('domain', sa.JSON(), nullable=True),
    sa.Column('ip', sa.JSON(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('inbound_tags', sa.JSON(), nullable=True),
    sa.Column('client_emails', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['outbound_tag'], ['outbounds.tag'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routing_rules_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routing_rules_id'))

    op.drop_table('routing_rules')
    with op.batch_alter_table('outbounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbounds_tag'))
        batch_op.drop_index(batch_op.f('ix_outbounds_id'))

    op.drop_table('outbounds')
    # ### end Alembic commands ###
