"""add_xray_resource

Revision ID: 8f39a68cd928
Revises: d4dbdf7f451f
Create Date: 2026-04-02 20:03:28.693288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f39a68cd928'
down_revision: Union[str, Sequence[str], None] = 'd4dbdf7f451f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xray_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=True),
    sa.Column('update_interval', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xray_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xray_resources_filename'), ['filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_xray_resources_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xray_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xray_resources_id'))
        batch_op.drop_index(batch_op.f('ix_xray_resources_filename'))

    op.drop_table('xray_resources')
    # ### end Alembic commands ###
