"""add_global_settings

Revision ID: 90781ea6f2b0
Revises: 8f39a68cd928
Create Date: 2026-04-06 10:55:39.115641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90781ea6f2b0'
down_revision: Union[str, Sequence[str], None] = '8f39a68cd928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_strategy', sa.String(), nullable=False),
    sa.Column('log_level', sa.String(), nullable=True),
    sa.Column('access_log', sa.String(), nullable=True),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.Column('stats_user_uplink', sa.Boolean(), nullable=True),
    sa.Column('stats_user_downlink', sa.Boolean(), nullable=True),
    sa.Column('dns_settings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_settings')
    # ### end Alembic commands ###
