"""add_traffic_summaries_and_auto_reset

Revision ID: 9f906cad445f
Revises: 6673c1cb3d9e
Create Date: 2026-03-16 13:21:11.917945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f906cad445f'
down_revision: Union[str, Sequence[str], None] = '6673c1cb3d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_up', sa.BigInteger(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('summary_down', sa.BigInteger(), server_default='0', nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_total_up', sa.BigInteger(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('summary_total_down', sa.BigInteger(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('auto_reset_traffic', sa.Boolean(), server_default='false', nullable=True))
        batch_op.add_column(sa.Column('reset_period', sa.String(), server_default='month', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_period')
        batch_op.drop_column('auto_reset_traffic')
        batch_op.drop_column('summary_total_down')
        batch_op.drop_column('summary_total_up')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('summary_down')
        batch_op.drop_column('summary_up')

    # ### end Alembic commands ###
