"""fix_outbounds

Revision ID: d4dbdf7f451f
Revises: 6c6fcdcd9592
Create Date: 2026-04-02 12:02:41.305938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4dbdf7f451f'
down_revision: Union[str, Sequence[str], None] = '6c6fcdcd9592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proxy_settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbounds', schema=None) as batch_op:
        batch_op.drop_column('proxy_settings')

    # ### end Alembic commands ###
