"""add_subscription_system_m2m

Revision ID: e72da506a826
Revises: 90781ea6f2b0
Create Date: 2026-04-06 22:10:30.865637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72da506a826'
down_revision: Union[str, Sequence[str], None] = '90781ea6f2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('client_type', sa.String(), server_default='json', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('injection_tag', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_templates'))
    )
    with op.batch_alter_table('subscription_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_templates_client_type'), ['client_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_templates_name'), ['name'], unique=True)

    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['subscription_templates.id'], name=op.f('fk_user_groups_template_id_subscription_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_groups'))
    )
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_groups_name'), ['name'], unique=True)

    op.create_table('user_group_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], name=op.f('fk_user_group_association_group_id_user_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_group_association_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('pk_user_group_association'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_association')
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_groups_name'))
        batch_op.drop_index(batch_op.f('ix_user_groups_id'))

    op.drop_table('user_groups')
    with op.batch_alter_table('subscription_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_templates_name'))
        batch_op.drop_index(batch_op.f('ix_subscription_templates_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_templates_client_type'))

    op.drop_table('subscription_templates')
    # ### end Alembic commands ###
