"""fix_reset_traffic

Revision ID: f9100aa64518
Revises: 347c97f904f8
Create Date: 2026-04-21 15:41:33.153498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9100aa64518'
down_revision: Union[str, Sequence[str], None] = '347c97f904f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nginx_payload', sa.JSON(), nullable=True))

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reality_server_address', sa.String(), nullable=False))
        batch_op.drop_column('reality_server_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reality_server_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('reality_server_address')

    with op.batch_alter_table('node_configs', schema=None) as batch_op:
        batch_op.drop_column('nginx_payload')

    # ### end Alembic commands ###
